upload_image:
    resource: "@UploadImageBundle/Controller/"
    type:     annotation
    prefix:   /

infinity:
    resource: "@InfinityBundle/Controller/"
    type:     annotation
    prefix:   /infinity

